tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-secondary-fixed": "#241a00",
                "on-secondary-container": "#745c00",
                "outline": "#6d7a72",
                "on-surface-variant": "#3d4a42",
                "secondary-container": "#fed65b",
                "surface-dim": "#d9dadb",
                "primary": "#006948",
                "on-secondary": "#ffffff",
                "surface": "#f8f9fa",
                "on-primary": "#ffffff",
                "outline-variant": "#bccac0",
                "surface-container-highest": "#e1e3e4",
                "on-primary-container": "#f5fff7",
                "surface-container-lowest": "#ffffff",
                "secondary": "#735c00",
                "on-primary-fixed": "#002114",
                "on-tertiary-fixed": "#002116",
                "on-tertiary-fixed-variant": "#00513b",
                "on-secondary-fixed-variant": "#574500",
                "error": "#ba1a1a",
                "surface-tint": "#006c4a",
                "tertiary": "#17684e",
                "inverse-on-surface": "#f0f1f2",
                "on-tertiary": "#ffffff",
                "primary-fixed": "#85f8c4",
                "secondary-fixed": "#ffe088",
                "tertiary-fixed-dim": "#8bd6b6",
                "surface-bright": "#f8f9fa",
                "on-primary-fixed-variant": "#005137",
                "surface-variant": "#e1e3e4",
                "surface-container": "#edeeef",
                "background": "#f8f9fa",
                "on-tertiary-container": "#f5fff8",
                "on-error": "#ffffff",
                "error-container": "#ffdad6",
                "primary-container": "#00855d",
                "primary-fixed-dim": "#68dba9",
                "secondary-fixed-dim": "#e9c349",
                "tertiary-fixed": "#a6f2d1",
                "inverse-primary": "#68dba9",
                "surface-container-high": "#e7e8e9",
                "surface-container-low": "#f3f4f5",
                "on-surface": "#191c1d",
                "tertiary-container": "#378166",
                "on-error-container": "#93000a",
                "on-background": "#191c1d",
                "inverse-surface": "#2e3132"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "container-max": "1280px",
                "stack-md": "16px",
                "section-padding-desktop": "80px",
                "stack-sm": "8px",
                "stack-lg": "32px",
                "section-padding-mobile": "40px",
                "gutter": "24px"
            },
            fontFamily: {
                "display-lg-mobile": ["Plus Jakarta Sans"],
                "body-md": ["Inter"],
                "headline-sm": ["Plus Jakarta Sans"],
                "caption": ["Inter"],
                "display-lg": ["Plus Jakarta Sans"],
                "body-lg": ["Inter"],
                "headline-md": ["Plus Jakarta Sans"],
                "label-md": ["Inter"]
            },
            fontSize: {
                "display-lg-mobile": ["32px", { lineHeight: "1.25", fontWeight: "700" }],
                "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
                "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
                "caption": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
                "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "headline-md": ["30px", { lineHeight: "1.3", fontWeight: "600" }],
                "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }]
            }
        }
    }
}